Repository BiancaRomeroG/Proyecto_SI1, pull requests merged in 2021-11, with the labels that each got.

#13 Crear home page
  app/Http/Controllers/homeController.php
  public/img/search.png
  public/img/slide1.jpg
  public/img/slide2.jpg
  public/img/slide3.jpg
  public/img/slide4.jpg
  public/img/slide5.jpg
  public/img/target.png
  resources/views/home.blade.php
  resources/views/login.blade.php
  routes/web.php
Labels: enhancement

#19 favicon agregado al login y home
  public/favicon.ico
  resources/views/home.blade.php
  resources/views/login.blade.php
Labels: enhancement

#23 Create .gitpod.yml
  .gitpod.yml
Labels: enhancement

#24 Correcciones
  database/migrations/2014_10_12_100000_create_password_resets_table.php
  database/migrations/2021_11_06_234501_create_personas_table.php
  database/migrations/2021_11_07_003225_create_rols_table.php
  database/migrations/2021_11_07_003439_create_usuarios_table.php
  database/migrations/2021_11_07_004117_create_acciones_table.php
  database/migrations/2021_11_07_005600_create_profesores_table.php
  database/migrations/2021_11_07_005939_create_materias_table.php
  database/migrations/2021_11_07_010214_create_cursos_table.php
  database/migrations/2021_11_07_013202_create_desarrollas_table.php
  database/migrations/2021_11_07_013443_create_tutores_table.php
  database/migrations/2021_11_07_013723_create_alumnos_table.php
  database/migrations/2021_11_07_013945_create_cardexes_table.php
  database/migrations/2021_11_07_014234_create_boletines_table.php
  database/migrations/2021_11_07_014643_create_notas_table.php
  database/migrations/2021_11_07_014958_create_administrativos_table.php
  database/migrations/2021_11_07_015655_create_pagos_table.php
  database/migrations/2021_11_07_015814_create_pago_salarios_table.php
  database/migrations/2021_11_07_020217_create_pago_mensualidads_table.php
  database/migrations/2021_11_07_021500_create_inscripciones_table.php
  database/seeders/AdministrativosSeeder.php
  database/seeders/AlumnosSeeder.php
  database/seeders/BoletinesSeeder.php
  database/seeders/CardexSeeder.php
  database/seeders/CursosSeeder.php
  database/seeders/DesarrollaSeeder.php
  database/seeders/InscripcionesSeeder.php
  database/seeders/MateriasSeeder.php
  database/seeders/NotasSeeder.php
  database/seeders/PagoMensualidadSeeder.php
  database/seeders/PagoSalariosSeeder.php
  database/seeders/PagosSeeder.php
  database/seeders/PersonaSeeder.php
  database/seeders/ProfesoresSeeder.php
  database/seeders/TutoresSeeder.php
  database/seeders/UsuarioSeeder.php
Labels: enhancement

#27 plantilla base agregada en views
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/login.blade.php
  resources/views/master.blade.php
Labels: enhancement

#31 Pagina de registro creada
  app/Http/Controllers/homeController.php
  database/migrations/2021_11_07_013202_create_desarrollas_table.php
  resources/views/registro.blade.php
  routes/web.php
Labels: enhancement

#29 Mensajes de informacion toast agregados
  resources/views/master.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement

#40 registro de personas guardado
  app/Http/Controllers/homeController.php
  app/Http/Controllers/registroController.php
  app/Models/Persona.php
  resources/views/registro.blade.php
  routes/web.php
Labels: enhancement

#38 Paginas creadas para el profe y el admin
  app/Http/Controllers/homeController.php
  public/img/favicon.ico
  resources/views/administrativo.blade.php
  resources/views/home.blade.php
  resources/views/layouts/home_plantilla.blade.php
  resources/views/layouts/master.blade.php
  resources/views/login.blade.php
  resources/views/profesor.blade.php
  resources/views/registro.blade.php
  routes/web.php
Labels: enhancement

#43 logout agregado
  app/Http/Controllers/Auth/ConfirmPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/loginController.php
  app/Http/Controllers/sessionController.php
  resources/views/layouts/home_plantilla.blade.php
  routes/web.php
Labels: enhancement

#44 Add DirectorMiddleware
  app/Http/Kernel.php
  app/Http/Middleware/DirectorMiddleware.php
  routes/web.php
Labels: enhancement

#45 Secretaria cambiado a administrador
  database/seeders/RolSeeder.php
Labels: enhancement

#49 test
  routes/web.php
Labels: invalid

#48 Pagina de registrar materias con funcionalidad lista
  app/Http/Controllers/materiaController.php
  app/Models/materias.php
  resources/views/layouts/master.blade.php
  resources/views/materiaRegistro.blade.php
  routes/web.php
Labels: enhancement

#51 Create ApoderadoPage
  app/Http/Controllers/homeController.php
  resources/views/apoderado.blade.php
  routes/web.php
Labels: enhancement

#56 Fix routes/web LoginController
  routes/web.php
Labels: bug

#57 pagina de alumno agregada
  app/Http/Controllers/homeController.php
  resources/views/alumno.blade.php
  routes/web.php
Labels: enhancement

#63 Plantilla de datos personales creada - Revision de action form
  resources/views/alumno.blade.php
  resources/views/layouts/datosPersonales_plantilla.blade.php
Labels: enhancement
